apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
stringData:
  # Example secret - replace with your actual values
  API_KEY: "c98856dad6208fc1bb42206d6a3aa6c0f3a9439-6f6e-458c-a951-67d2d575c300"
